# Generated by Django 5.0.4 on 2024-04-26 05:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_persona_groups_persona_is_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='date_joined',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
