# Generated by Django 5.0.4 on 2024-06-13 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_comment_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(default='media/imgsC/Blancos.png', upload_to='imgsC', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='media/imgsP/Blancos.png', upload_to='imgsP', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='', max_length=100, unique=True),
        ),
    ]
