# Generated by Django 5.0.4 on 2024-06-13 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_postlikecount_post_comment_slug_likecomments_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='name',
            new_name='username',
        ),
    ]
