# Generated by Django 5.0.4 on 2024-06-14 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_name_persona_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='persona',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='persona',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='persona',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
