# Generated by Django 5.0.4 on 2024-06-14 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_persona_groups_persona_user_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likecomments',
            options={'verbose_name_plural': 'LikeComments'},
        ),
        migrations.AlterModelOptions(
            name='likeposts',
            options={'verbose_name_plural': 'LikePosts'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.ImageField(upload_to='imgsC', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='imgsP', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(max_length=40),
        ),
    ]
