# Generated by Django 5.0.4 on 2024-06-14 06:25

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_persona_image_alter_comment_image_alter_post_image'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('postobjects', django.db.models.manager.Manager()),
            ],
        ),
    ]
