# Generated by Django 5.0.4 on 2024-06-21 08:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_post_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='awards',
        ),
        migrations.AlterField(
            model_name='persona',
            name='exp',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, to='api.tag'),
        ),
        migrations.DeleteModel(
            name='Award',
        ),
    ]
