# Generated by Django 5.0.4 on 2024-06-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_post_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='image',
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.FileField(blank=True, upload_to='imgsC', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(blank=True, upload_to='imgsP', verbose_name='Imagen'),
        ),
    ]
