export const GET_POST_LIST_SUCCESS = 'GET_POST_LIST_SUCCESS';
export const GET_POST_LIST_FAIL = 'GET_POST_LIST_FAIL';

export const GET_AUTHOR_POST_LIST_SUCCESS = 'GET_AUTHOR_POST_LIST_SUCCESS';
export const GET_AUTHOR_POST_LIST_FAIL = 'GET_AUTHOR_POST_LIST_FAIL';

export const GET_POST_LIST_TAG_SUCCESS = 'GET_POST_LIST_TAG_SUCCESS';
export const GET_POST_LIST_TAG_FAIL = 'GET_POST_LIST_TAG_FAIL';

export const GET_POST_SUCCESS = 'GET_POST_SUCCESS';
export const GET_POST_FAIL = 'GET_POST_FAIL';

export const GET_SEARCH_POST_SUCCESS = 'GET_SEARCH_POST_SUCCESS';
export const GET_SEARCH_POST_FAIL = 'GET_SEARCH_POST_FAIL';